# ./.tmuxinator.yml

name: DEEP BLUE AI Lab
root: ~/

pre_window: export PS1=" \[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;45m\]>>>\[$(tput sgr0)\] \[$(tput sgr0)\]"

startup_window: Gazebo
startup_pane: 0

windows:
  - Gazebo: 
      root: ~/ros/ros2_ws
      panes:
        - clear; source ~/.bashrcROS; echo "Display Gazebo"
  - Driver: 
      root: ~/ros/ros2_ws
      layout: 0a91,122x31,0,0{61x31,0,0,0,60x31,62,0,1}
      panes:
        - clear; source ~/.bashrcROS; echo "controller spawner for gazebo ros2 controller manager"
        - clear; source ~/.bashrcROS; sleep 25; echo "robot pose initializer for Localization node"
  - Localization: 
      root: ~/ros/ros2_ws
      panes:
        - clear; source ~/.bashrcROS; echo "Localization launch"
  - Navigation: 
      root: ~/ros/ros2_ws
      panes:
        - clear; source ~/.bashrcROS; echo "Navigation launch"
  - BehaviorTree: 
      root: ~/ros/ros2_ws
      panes:
        - clear; source ~/.bashrcROS; sleep 35; echo "Behavior Tree Launch"
  - About:
      layout: 0a91,122x31,0,0{61x31,0,0,0,60x31,62,0,1}
      root: ~/ros/ros2_ws
      panes:
        - clear; source ~/.bashrcROS; cowsay Wellcome Idiots! ; echo "                              OPEN SOURCE ROBOTICS FOR MYANMAR"
        - clear; source ~/.bashrcROS; neofetch
        - clear; source ~/.bashrcROS; ranger ranger ros2/ros2_ws/src/rom2109_simulation/
  
